"""
Module for converting PLIP protein-ligand interaction reports to CSV format.

This module provides functionality to parse PLIP (Protein-Ligand Interaction Profiler)
TXT report files and convert them into structured CSV files organized by interaction type.

The main workflow consists of two steps:
1. Parse a PLIP TXT report file into a nested dictionary structure using `plip2dictlist()`
2. Write the parsed data to individual CSV files using `write2csv()`

Typical usage example:

    # Parse PLIP report
    plip_data = plip2dictlist(Path("report.txt"))

    # Write to CSV files
    write2csv(plip_data, Path("output"))

"""

import csv
from collections import defaultdict
from collections.abc import Iterator
from contextlib import ExitStack
from dataclasses import dataclass
from pathlib import Path


@dataclass
class CommonFields:
    """Common fields across all interaction types."""

    common_field: tuple[str, ...] = (
        "resnr",
        "restype",
        "reschain",
        "resnr_lig",
        "restype_lig",
        "reschain_lig",
        "dist",
        "ligcoo",
        "protcoo",
    )


def iter_plip_interactions(path: Path) -> Iterator[tuple[str, list[str], dict[str, str]]]:
    """Yield parsed PLIP interactions one row at a time.

    Parameters
    ----------
    path : Path
        The file path to the TXT report file generated by PLIP using the `-t` flag.

    Yields
    ------
    tuple[str, list[str], dict[str, str]]
        A tuple containing interaction type, section header, and one parsed row.

    Raises
    ------
    ValueError
        If the number of columns in a row does not match the section header.
    """

    with path.open("r", encoding="UTF-8") as file:
        for line in file:
            if line.startswith("**") and line.endswith("**\n"):
                interaction_type = line.strip().replace("**", "").strip().replace(" ", "_").lower()

                # Skip the table separator line.
                try:
                    next(file)
                    header_line = next(file)
                except StopIteration:
                    return
                header = [column_name.strip().lower() for column_name in header_line.strip().split("|") if column_name]

                # Skip the table separator line.
                try:
                    next(file)
                    line = next(file)
                except StopIteration:
                    return

                while line.strip():
                    values = [value.strip() for value in line.strip().split("|") if value.strip()]

                    if values and len(values) > 1:
                        if len(values) != len(header):
                            raise ValueError(f"error number of columns, expected {len(header)}, got {len(values)}")
                        row = {header[i]: value for i, value in enumerate(values)}
                        yield interaction_type, header, row

                    try:
                        line = next(file)
                    except StopIteration:
                        return


def plip2dictlist(path: Path) -> defaultdict[str, list[dict[str, str]]]:
    """Read a PLIP TXT report file and parse it into a structured dictionary.

    This function reads the TXT file output by PLIP (Protein-Ligand Interaction Profiler)
    and packages all interaction data as a nested dictionary organized by interaction type.

    Parameters
    ----------
    path : Path
        The file path to the TXT report file generated by PLIP using the `-t` flag.

    Returns
    -------
    defaultdict[str, list[dict[str, str]]]
        A dictionary where:
        - Keys are interaction types (e.g., "Hydrogen_Bonds", "Hydrophobic_Interactions")
        - Values are lists of dictionaries, where each dictionary represents a single
          interaction with column names as keys and interaction details as values.

    Raises
    ------
    ValueError
        If the number of columns in a row does not match the number of columns in the header .

    Notes
    -----
    The function expects a PLIP TXT report with the following structure:
    - Section headers enclosed in double asterisks (e.g., "** Hydrogen Bonds **")
    - A separator line after each header
    - A header row with column names separated by pipes (|)
    - A separator line before data rows
    - Data rows with values separated by pipes (|)
    """

    # local variable
    plip_dict = defaultdict(list)

    for interaction_type, _, row in iter_plip_interactions(path):
        plip_dict[interaction_type].append(row)

    return plip_dict


def plip2csv_stream(path: Path, output_dir: Path) -> None:
    """Parse a PLIP TXT report and write CSV files directly without buffering rows.

    This function is designed for large PLIP reports where keeping all parsed data in
    memory is undesirable. Rows are written to per-interaction CSV files and the summary
    CSV as soon as they are parsed.

    Parameters
    ----------
    path : Path
        The file path to the TXT report file generated by PLIP using the `-t` flag.
    output_dir : Path
        The directory where output CSV files will be written.
    """

    common_fields = CommonFields().common_field
    output_dir.mkdir(parents=True, exist_ok=True)

    with ExitStack() as stack:
        summary_file = output_dir / "summary.csv"
        summary_handle = stack.enter_context(summary_file.open("w", encoding="UTF-8", newline=""))
        summary_writer = csv.DictWriter(summary_handle, fieldnames=common_fields)
        summary_writer.writeheader()

        interaction_writers: dict[str, csv.DictWriter] = {}
        interaction_headers: dict[str, list[str]] = {}

        for interaction_type, header, row in iter_plip_interactions(path):
            writer = interaction_writers.get(interaction_type)
            if writer is None:
                output_file = output_dir / f"{interaction_type}.csv"
                output_handle = stack.enter_context(output_file.open("w", encoding="UTF-8", newline=""))
                writer = csv.DictWriter(output_handle, fieldnames=header)
                writer.writeheader()
                interaction_writers[interaction_type] = writer
                interaction_headers[interaction_type] = header

            if interaction_headers[interaction_type] != header:
                raise ValueError(
                    f"inconsistent header for {interaction_type}: expected {interaction_headers[interaction_type]}, got {header}"
                )

            writer.writerow(row)
            summary_writer.writerow({field: row.get(field, "") for field in common_fields})


def write2csv(plip_dict: defaultdict[str, list[dict[str, str]]], output_dir: Path) -> None:
    """Write the parsed PLIP interaction data to CSV files.

    This function takes the structured dictionary output from `plip2dictlist` and writes
    each interaction type to a separate CSV file in the specified output directory.

    Parameters
    ----------
    plip_dict : defaultdict[str, list[dict[str, str]]]
        A dictionary where keys are interaction types and values are lists of dictionaries
        representing individual interactions.
    output_dir : Path
        The directory where the CSV files will be saved. Each file will be named after
        its corresponding interaction type (e.g., "Hydrogen_Bonds.csv").

    Returns
    -------
    None

    Notes
    -----
    - The function creates the output directory if it does not exist.
    - Each CSV file will have a header row with column names corresponding to the keys
      in the interaction dictionaries.
    """

    # declare local variable
    common_fields = CommonFields().common_field
    # create output directory if it does not exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # setup the summary writer
    summary_file = output_dir / "summary.csv"
    with summary_file.open("w", encoding="UTF-8", newline="") as csvfile:
        summary_writer = csv.DictWriter(csvfile, fieldnames=common_fields)
        summary_writer.writeheader()

        for interaction_type, interactions in plip_dict.items():
            if interactions:
                # get header from keys of first interaction dictionary
                header = interactions[0].keys()
                output_file = output_dir / f"{interaction_type}.csv"

                with output_file.open("w", encoding="UTF-8", newline="") as csvfile:
                    writer = csv.DictWriter(csvfile, fieldnames=header)
                    writer.writeheader()
                    writer.writerows(interactions)
                    # write summary data
                    for interaction in interactions:
                        summary_writer.writerow({field: interaction.get(field, "") for field in common_fields})
